[package]
name = "day-12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.8.1"

[[bin]]
name = "p1"
path = "src/part1.rs"

[[bin]]
name = "p2"
path = "src/part2.rs"

