[package]
name = "year-2024"
version = "0.1.0"
edition = "2024"

[lib]
name = "aoc_days"
path = "src/lib.rs"

[dependencies]
aoc-macro = { path = "../tools/aoc-macro" }
crossterm = "0.28.1"
rayon = "1.10.0"

[[bin]]
name = "day6_runner"
path = "src/day6_runner.rs"
