[package]
name = "day-13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"

[[bin]]
name = "p1"
path = "src/part1.rs"

[[bin]]
name = "p2"
path = "src/part2.rs"

